version: '2'
services:
  couchdb:
    image: hyperledger/fabric-couchdb
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password  # CouchDB credentials

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.org1.example.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin  # Add CouchDB username
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password  # Add CouchDB password
    ports:
      - "7051:7051"
